gamma: 0.9
epsilon: 1.0
learning_rate: 1e-3
mode: 'static'
num_epochs: 5000
mem_size: 2000                                                                                                       
max_moves: 30
batch_size:  30
sync_freq: 600
slowness_sync_pram: 2
partially_blind: False
vanilla_exploration: True
sync_improvised: False
min_num_epi_for_sync_rule_application: 20
min_num_win_epi_for_sync_rule_application: 5
winratio_at_last_ten_epi: 0.3
excluding_last_n_epi_for_average_prev_moves: 10

loss_fn: torch.nn.MSELoss()
act_func: 'leaky'
layerwisesize: [200, 100, 8]

num_pieces: 5
grid_dimension: 10
agent: P
exit: E
agent_pos: (9,0)
exit_pos: (0,9)
sources: {'S1':25,'S2':25,'S3':5}
sources_pos: {'S1':[6,0],'S2':[6,9],'S3':[0,6]}
